export const ApiRoutes = {
  FAQ: `/faq`,
  INQUIRY: `/contact-us`,
  ABOUTUS: `cms/about-us`,
  SAME_DAY_RENTALS: `cms/same-day-rentals`,
  PRIVACY_POLICY: `cms/privacy-policy`,
  CANCELLATION_POLICY: `cms/cancellation-policy`,
  RENTAL_POLICY: `cms/rental-policy`,
  SAFETY_POLICY: `cms/safety-policy`,
  TERMS_AND_CONDITIONS: `cms/terms-and-conditions`,
  SOCIAL_MEDIA: `/settings`,
  PRODUCT_LIST: `/products`,
  CREATE_RESERVATION: `/create-reservation`,
  PRODUCT_DETAILS: `/product-details`,
  FEEDBACK: `/reviews`,
  RESERVATION_DETAILS: '/reservation-details',
  CHECK_PRODUCT_AVAILABILITY: '/check-product-availability',
  CREATE_INTENT: '/create-intent',
  VERIFY_ORDER: '/verify-order',
  PASSENGERS: '/passengers',
  FUELS: '/fuels',
  CHECK_GOLF_CART_AVAILABILITY: '/check-golf-cart-availability',
  TERMS_OF_SERVICE: 'cms/terms-of-service',
};

